# -*- coding: utf-8 -*-
"""Calories Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LEuN1Yz9aGmqCtoEgQLJIijHomdRuRla
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn  import metrics

calories = pd.read_csv('/content/calories.csv')
exercise = pd.read_csv('/content/exercise.csv')

calories.head()

exercise.head()

calories.tail()

calories.describe()

calories.info()

calories.isnull().sum()

exercise.tail()

exercise.describe()

exercise.info()

exercise.isnull().sum()

calories_data =pd.concat([exercise,calories['Calories']],axis =1)

calories_data.head()

calories_data.shape

calories_data.info()

# data analysis
calories_data.describe()

sns.set()

sns.countplot(calories_data ['Gender'])#countplot is for yes or no

sns.distplot(calories_data['Age'])

sns.distplot(calories_data['Height'])

sns.distplot(calories_data['Weight'])

correlation = calories_data.corr( )

plt.figure(figsize=(10, 10))
sns.heatmap(correlation, cbar=True, square=True, fmt='.1f', annot_kws={'size': 8}, cmap='Blues')

"""converting the text data to numeric data"""

calories_data.replace({'Gender':{'male':0,'female':1}},inplace =True)

calories_data.head()

X =calories_data.drop(columns =['User_ID','Calories'],axis=1)
Y = calories_data['Calories']

print (X)

print(Y)

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

print(X.shape,X_train.shape,X_test.shape)

print(Y.shape,Y_train.shape,Y_test.shape)

"""xgboostRegressor"""

model =XGBRegressor()

model.fit(X_train,Y_train)

"""Evaluation model"""

test =model.predict(X_test)

print(test)

"""Mean absolute error"""

m = metrics.mean_absolute_error(Y_test,test)

print("mean absolute error :",m)

