# -*- coding: utf-8 -*-
"""Car Modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f3Fg_2rU2ap3ESm6LxaNnvNO-4jt2zk5

Objective - insurance claim
"""

import pandas as pd

df = pd.read_csv("/content/insurance_claims.csv")

df.head()

df.tail()

df.shape

df.isnull().sum()

df.describe()

df.head()

df.replace({'region':{'Urban':0,'Rural':1,'Suburban':2}},inplace = True)

df.head()

"""#"""

