# -*- coding: utf-8 -*-
"""Image Processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bG5L4xMMK5seITQTArXAQBmI5rluFJC7

**Topics**


*   Reading an image file and converting it to a numpy array
*   Resizing an image


*   RGB to Grayscale conversion

Getting an Image
"""

!wget 'https://imgs.search.brave.com/PBfAoW_hop4rIX2BDfv2vkbw3yRqqCKHQXnlba6pO0c/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE2/MjY3MzY2Mzc4NDUt/NTMwNDViYjk2OTVi/P3E9ODAmdz0xMDAw/JmF1dG89Zm9ybWF0/JmZpdD1jcm9wJml4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRsOGZH/TjFkR1VsTWpCa2Iy/ZDhaVzU4TUh4OE1I/eDhmREE9.jpeg'

"""Libraries used

1.Maplotlib.image

2.pillow

3.OpenCV
"""

import matplotlib.image as mpimg
import matplotlib.pyplot as plt

img = mpimg.imread('/content/Dog.jpeg')

type(img)

print(img.shape)

print(img)

#displaying the image from many array
img_plot = plt.imshow(img)
plt.show()

"""How to resize the image using pillow"""

from PIL import Image

img = Image.open('/content/Dog.jpeg')
img_resized = img.resize((200,200))

img_resized.save('dog_image_resized.jpeg')

img_res = mpimg.imread('/content/dog_image_resized.jpeg')
img_res_plot = plt.imshow(img_res)
plt.show()

print(img_res.shape)

"""Converting a RGB to Grayscale using Grayscale"""

import cv2

img = cv2.imread('/content/Dog.jpeg')

type(img)

img.shape

grayscale_image = cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)

type(grayscale_image)

grayscale_image.shape

from google.colab.patches import cv2_imshow

#  displaying the image
cv2_imshow(grayscale_image)

# saving the grayscale imagecv
cv2.imwrite('dog_grayscale_image.jpeg',grayscale_image)

