# -*- coding: utf-8 -*-
"""Spend Smarter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5TQHwiaTcmW9kaPzFXd_fsLNFSV5HFO
"""

import numpy as np
import pandas as pd
import matplotlib as plt
from sklearn.cluster import KMeans

customer_data = pd.read_csv('/content/Mall_Customers.csv')

customer_data.head()

customer_data.tail()

customer_data.info()

customer_data.describe()

customer_data.shape

customer_data.isnull().sum()

""" Choosing the  annual column and spendding score"""

X = customer_data.iloc[:,[3,4]].values
print(X)

"""now we have to find the correct numbers of cluster

for that we use a formula WCSS=within cluster sum of squares
"""

# finding the different wcss  values
wcss= []

for i in range (1,11):
  Kmeans =KMeans(n_clusters=i, init='k-means++',random_state=42)
  Kmeans.fit(X)
  wcss.append(Kmeans.inertia_)

#plot an elbow graph
sns.set()
plt.plot(range(1,11),wcss)
plt.title("the Elbow point graph")
plt.xlabel('Number of clusters')
plt.ylabel('wcss')
plt.plot()

"""the optimum number of clusters is 5 . as elebow point lies between 4 and 6

Training the k-means clustering model
"""

kmeans =KMeans(n_clusters =5 ,init ='k-means++',random_state=0)

# return a label for each data point based on their cluster
Y = kmeans.fit_predict(X)
print(Y)

"""there are 5 clusters - 0,1,2,3,4

Visual representation of clusters
"""

#plotting all the clusters and the centroids
plt.figure(figsize=(8,8))
plt.scatter(X[Y==0,0],X[Y==0,1],s =50,c='green',label ='Cluster1')
plt.scatter(X[Y==1,0],X[Y==1,1],s =50,c='red',label ='Cluster2')
plt.scatter(X[Y==2,0],X[Y==2,1],s =50,c='yellow',label ='Cluster3')
plt.scatter(X[Y==3,0],X[Y==3,1],s =50,c='blue',label ='Cluster4')
plt.scatter(X[Y==4,0],X[Y==4,1],s =50,c='brown',label ='Cluster5')
# plot the centriods
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=100,c = 'cyan',label ='centroids')
plt.title('Customer Groups')
plt.xlabel('Annual income')
plt.ylabel('Spending score')
plt.show()

"""the brown centroid people tend make less money so they spend less

the blue centroid people make less money but they spend more money

the gree centroid people make more money but they spend less money

the red centroid people make average money and they average more money

the yellow centroid people make more money and they spend more money
"""