# -*- coding: utf-8 -*-
"""Wine Test Quality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BCIUzyEO9DzwWhcuBxykWm6NNlZj04Je
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score

wine = pd.read_csv('/content/winequality-red.csv')

wine.head()

wine.tail()

wine.shape

wine.describe()

wine.isnull().sum()



"""pie chart

"""

wine['quality'].value_counts().plot(kind ='pie',autopct='%.2f')

plt.hist(wine['pH'],bins =50)

